services:
  postgres:
    image: postgres:15
    container_name: cycle-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pe6958@25
      POSTGRES_DB: cycle
    ports:
      - "5433:5432"
    volumes:
      - cycle_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: cycle-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mongodb:
    image: mongo:7
    container_name: cycle-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: cycle-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  cycle_postgres_data:
    external: true
  mongo_data:
  redis_data:
  pgadmin_data:
